export const FETCH_WEATHER = 'COMMAND/FETCH_WEATHER_FOR_LAT_LNG';
export const API_ERROR = 'EVENT/API_ERROR_RECEIVED';
export const WEATHER_DATA_RECEIVED = 'EVENT/WEATHER_DATA_RECEIVED';
export const WEATHER_ID_RECEIVED = 'EVENT/WEATHER_ID_RECEIVED';
export const FETCH_DRONE_DATA = 'COMMAND/FETCH_DRONE_DATA';
export const FETCH_DRONE_DATA_SUCCESS = 'EVENT/FETCH_DRONE_DATA_SUCCESS';
export const POLLING_START = 'COMMAND/START_POLLING';
export const POLLING_STOP = 'COMMAND/STOP_POLLING';

export const SUBMIT_FORM_START = 'SUBMIT_FOR';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FOR_SUCCESS';

